---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/2/20 16:41
---
--- 1.参数列表
--- 1.1 优惠券id
local voucherId = ARGV[1]
--- 1.2 用户Id
local userId = ARGV[2]
--- 1.3 订单id
local orderId = ARGV[3]

--- 2.数据库key
--- 2.1库存key
local stockKey = 'seckill:stock:' .. voucherId
--- 2.2订单key
local orderKey = 'seckill:order' .. voucherId

--- 3.脚本业务
--- 3.1 判断库存是否充足
if(tonumber(redis.call('get', stockKey)) <= 0) then
    --- 库存不足返回1
    return 1
end
--- 3.2 判断是否重复下单
if (redis.call('sismember', orderKey, userId) == 1) then
    --- 重复下单返回2
    return 2
end
--- 3.3 扣减库存
redis.call('incrby', stockKey, -1)
--- 3.4 存入用户id 使用set集合
redis.call('sadd', orderKey, userId)

--- 3.5 发送消息到Stream队列中 XADD stram
redis.call("xadd", 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0
